tap "buo/cask-upgrade"
tap "eddieantonio/eddieantonio"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
brew "aria2"
brew "autoconf"
brew "autoenv"
brew "autojump"
brew "automake"
brew "boost"
brew "boost-python"
brew "cmake"
brew "curl"
brew "docker", link: false
brew "fabric"
brew "fzf"
brew "gcc"
brew "git"
brew "git-quick-stats"
brew "libtool"
brew "htop"
brew "intltool"
brew "ipython"
brew "kite"
brew "kubernetes-cli"
brew "ruby"
brew "macvim", link: false
brew "mas"
brew "mitmproxy"
brew "mycli"
brew "mysql", restart_service: true
brew "nginx"
brew "node"
brew "numpy"
brew "ranger"
brew "redis", restart_service: true
brew "rename"
brew "screen"
brew "swig"
brew "telnet"
brew "the_silver_searcher"
brew "thefuck"
brew "tmux"
brew "tor"
brew "tree"
brew "vim", link: false
brew "vnstat", restart_service: true
brew "wget"
brew "when"
brew "wtf"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "eddieantonio/eddieantonio/imgcat"
cask "alfred"
cask "anaconda"
cask "cheatsheet"
cask "dash"
cask "docker"
cask "dropbox"
cask "font-awesome-terminal-fonts"
cask "font-hack-nerd-font"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "kindle"
cask "kite"
cask "pdf-expert"
cask "postman"
cask "pycharm"
cask "slack"
cask "sourcetree"
cask "spectacle"
cask "spotify"
cask "sublime-text"
cask "telegram"
cask "timing"
cask "tor-browser"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
mas "Be Focused Pro", id: 961632517
mas "Keynote", id: 409183694
mas "Microsoft OneNote", id: 784801555
mas "Noizio", id: 928871589
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Trello", id: 1278508951
